[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = -D WOKWI_SIM
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.11.0
    smougenot/TM1637

[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.11.0
    smougenot/TM1637

